import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const colorsPath = path.join(__dirname, '../components/theme/colors.json');
const outputPath = path.join(__dirname, '../app/theme-vars.css');

function generateCSS() {
  const colors = JSON.parse(fs.readFileSync(colorsPath, 'utf8'));
  let css = '/* Generated by scripts/generate-colors.mjs - DO NOT EDIT MANUALLY */\n\n:root {\n';

  // Generate Light colors
  Object.entries(colors.light).forEach(([key, value]) => {
    css += `  --${key}: ${value};\n`;
  });
  css += '}\n\n';

  // Generate Dark colors
  css += '.dark {\n';
  Object.entries(colors.dark).forEach(([key, value]) => {
    css += `  --${key}: ${value};\n`;
  });
  css += '}\n';

  fs.writeFileSync(outputPath, css);
  console.log(`✅ CSS variables generated successfully to ${outputPath}`);
}

try {
  generateCSS();
} catch (error) {
  console.error('❌ Error generating CSS variables:', error);
  process.exit(1);
}

